server:
  port: 8899
spring:
  #-------Spring Security相关配置-------
  #  security:
  #    user:
  #      name: SpringStone
  #      password: 1234
  #      roles: admin
  #-------数据源配置-------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///spring_stone?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
#-------Mybatis相关配置-------
mybatis:
  type-aliases-package: com.djn.entity
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true